version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: airlab-mysql
    environment:
      MYSQL_DATABASE: airlabsdb
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: airlab-project:latest
    container_name: airlab-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airlabsdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      API_KEY_AIRLABS: 3dabb7ef-783d-4518-adc5-9285f232ba17