services:
  app:
    image: airlab-project:latest
    container_name: airlab-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d5nel4smrvns73fmrh2g-a.oregon-postgres.render.com:5432/airlabsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0YtGGV2K2o4SNILlUsBBIIdUS6G24q3F
